training:
  path: "data/my_dataset.pt"   # Replace with your actual dataset path
  batch_size: 32
  epochs: 20
  lr: 0.001
  val_split: 0.2
  log_dir: "runs/"
  model_dir: "checkpoints/"

model:
  d_model: 64
  nhead: 4
  num_layers: 2
  dim_feedforward: 128
  dropout: 0.1
  regression: False
  n_classes: 4

simulation:
  num_samples: 1000
  sequence_length: 50
  output_path: "simulated_data/"

